# 서버 포트 설정
server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board2_mybatis?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  type-aliases-package: com.example.javaboardmybatis.board.dto
  mapper-locations: classpath:mapper/*.xml
